"""verification/QA.md from the check reports (generated by run_schematic.py)."""
from pathlib import Path
import json
P = Path(__file__).resolve().parents[1]
sc = json.loads((P / 'verification/schematic-check.json').read_text())
el = json.loads((P / 'verification/electrical-checks.json').read_text(encoding='utf-8'))
s1 = json.loads((P / 'verification/s1-checks.json').read_text(encoding='utf-8'))
ar = json.loads((P / 'verification/powierzchnia.json').read_text())
n1 = s1['negative_controls']
q = ['# P07-S1 — QA schematu (plik generowany przez src/make_qa.py)', '',
     f"ERC: {sc['erc_violations']} naruszeń na {sc['erc_sheets']} arkuszach. Netlista: {sc['components']} części, {sc['pin_checks']} pinów sprawdzonych pin po pinie względem `parts.py`, {len(sc['errors'])} błędów, {sc['nets']} sieci.", '',
     f"Kontrole elektryczne (`verify_electrical.py`): {sum(c['pass'] for c in el['checks'])}/{len(el['checks'])} PASS; mutacje {sum(t['caught'] for t in el['negative_controls'])}/{len(el['negative_controls'])} wykrytych; próba zerowa: {'czysta' if el['null_control_clean'] else 'NIECZYSTA'}. Tabela logiki: {el['analysis']['rows']} wierszy.",
     f"Kontrakt S1 / P12 (`verify_s1.py`): {sum(c['pass'] for c in s1['checks'])}/{len(s1['checks'])} PASS; mutacje {sum(t['detected'] for t in n1[:-1])}/{len(n1) - 1} wykrytych przez kontrolę docelową; próba zerowa: {'czysta' if not n1[-1]['detected'] else 'NIECZYSTA'}.",
     f"Powierzchnia (klasa 2/3, `powierzchnia.py`): suma courtyardów {ar['courtyard_bbox_sum_mm2']} mm² wobec {ar['usable_mm2']} mm² użytecznych — {ar['fill_percent']} % (metoda P06 R2: tam 41 %); wnętrze bez złączy krawędzi {ar['interior_fill_percent']} %, z rezystorami i małymi kondensatorami 1206 od spodu {ar['interior_fill_with_1206_bottom_percent']} %.", '',
     '| Kontrola elektryczna | Wynik | Uwagi |', '|---|---|---|'] + [f"| {c['id']} | {'PASS' if c['pass'] else 'FAIL'} | {c['note'][:220].replace('|', '/')} |" for c in el['checks']] + \
    ['', '| Kontrola S1 / P12 | Wynik |', '|---|---|'] + [f"| {c['id']} | {'PASS' if c['pass'] else 'FAIL'} |" for c in s1['checks']] + \
    ['', '## Próby ujemne elektryczne', '', '| Mutacja | Kontrola docelowa | Wykryta | Zgłosiły |', '|---|---|---|---|'] + \
    [f"| {t['mutation']} | {t['target']} | {'tak' if t['caught'] else 'nie'} | {', '.join(t['checks'])} |" for t in el['negative_controls']] + \
    ['', '## Próby ujemne S1 / P12', '', '| Mutacja | Kontrola docelowa | Wykryta | Zgłosiły |', '|---|---|---|---|'] + \
    [f"| {t['mutation']} | {t['target'] or '—'} | {'tak' if t['detected'] else 'nie'} | {', '.join(t['by']) or '—'} |" for t in n1] + \
    ['', 'Tylko schemat: PCB nie powstało (layout robi sesja lokalna, `docs/CHMURA.md` zasada 6). Kontrole plików nie zastępują pomiarów modułu (POMIARY-MODULU D/E) ani odbioru na sprzęcie.',
     'Ostrzeżenie kicad-cli „schemat posiada błędy numeracji” dotyczy oznaczeń `J_BP1`, `J_BP2`, `J_SV1`, `J_SV2` (nazwy z formatu S1, jak w P06 R2); ERC go nie zgłasza.']
(P / 'verification/QA.md').write_text('\n'.join(q) + '\n', encoding='utf-8')
print('QA.md written')
