M48
; DRILL file KiCad 10.0.6 date 2026-10-04T20:51:45
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-10-04T20:51:45+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X4.0Y-19.0
X4.0Y-96.0
X4.5Y-25.0
X4.5Y-60.0
X4.5Y-64.5
X4.5Y-75.0
X4.5Y-79.5
X4.5Y-90.0
X32.0Y-19.0
X32.0Y-96.0
M30
