M48
; DRILL file KiCad 10.0.6 date 2026-09-28T20:44:59
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-28T20:44:59+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C4.200
%
G90
G05
T1
X5.0Y-5.0
X5.0Y-115.0
X23.0Y-4.5
X34.08Y-4.5
X154.5Y-57.0
X154.5Y-75.7
X155.0Y-5.0
X155.0Y-115.0
T2
X4.5Y-23.38
X4.5Y-37.0
M30
