M48
; DRILL file KiCad 10.0.6 date 2026-09-27T13:41:55
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-27T13:41:55+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C4.200
%
G90
G05
T1
X5.0Y-5.0
X5.0Y-115.0
X128.8Y-113.5
X147.5Y-113.5
X155.0Y-5.0
X155.0Y-115.0
T2
X12.0Y-12.5
X25.62Y-12.5
M30
