M48
; DRILL file KiCad 10.0.6 date 2026-09-28T21:28:33
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-28T21:28:33+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X13.3Y-110.04
X39.5Y-110.04
X52.3Y-110.04
X70.1Y-110.04
T2
X5.0Y-5.0
X5.0Y-115.0
X14.7Y-8.0
X31.8Y-8.0
X58.7Y-8.0
X83.08Y-8.0
X155.0Y-5.0
X155.0Y-115.0
M30
