"""verification/QA.md from the check reports (generated by run_schematic.py)."""
from pathlib import Path
import json
P = Path(__file__).resolve().parents[1]
sc = json.loads((P / 'verification/schematic-check.json').read_text())
m1 = json.loads((P / 'verification/m1-checks.json').read_text(encoding='utf-8'))
parts = json.loads((P / 'docs/parts.json').read_text(encoding='utf-8'))
fit = [p for p in parts.values() if not p.get('dnp')]
neg = m1['negative_controls']
q = ['# M1-R1 — QA schematu (plik generowany przez src/make_qa.py)', '',
     f"Części na płytce: {len(fit)} (+ {len(parts) - len(fit)} DNP), w tym {sum(p['ref'].startswith('TP') for p in fit)} pól testowych bez elementu. Poza płytką: listwa X1, IBT-2, BMS, pakiet.",
     f"ERC: {sc['erc_violations']} naruszeń na {sc['erc_sheets']} arkuszach. Netlista: {sc['components']} części, {sc['pin_checks']} pinów sprawdzonych pin po pinie względem `parts.py`, {len(sc['errors'])} błędów, {sc['nets']} sieci.",
     f"Kontrole M1 (`verify_m1.py`): {sum(c['ok'] for c in m1['checks'])}/{len(m1['checks'])} PASS; mutacje {sum(t['detected'] for t in neg)}/{len(neg)} wykrytych przez kontrolę docelową; próba zerowa: {'czysta' if m1['null_control_clean'] else 'NIECZYSTA'}.", '',
     '| Kontrola | Wynik | Uwagi |', '|---|---|---|'] + [f"| {c['id']} | {'PASS' if c['ok'] else 'FAIL'} | {c['note'].replace('|', '/')} |" for c in m1['checks']] + \
    ['', '## Próby ujemne', '', '| Mutacja | Kontrola docelowa | Wykryta | Zgłosiły |', '|---|---|---|---|'] + \
    [f"| {t['mutation']} | {t['target']} | {'tak' if t['detected'] else 'nie'} | {', '.join(t['by']) or '—'} |" for t in neg] + \
    ['', 'Etap: schemat (krok 4 planu M1). PCB jeszcze nie powstało; kontrole plików nie zastępują odbioru na sprzęcie.']
(P / 'verification/QA.md').write_text('\n'.join(q) + '\n', encoding='utf-8')
print('QA.md written')
